### ISSUE TITLE
Difusion del proyecto.

### ISSUE THREAD

**Issue by UrsuzEremita** [UrsuzEremita/Proyecto_final#10]
Se agregara la liga hacia la publicación donde se difundió el proyecto.

**Comment by MIguelC137** [comment]
https://www.linkedin.com/posts/actmiguelramirez_cienciadedatos-proyectofinal-analytics-activity-7133705963806576640-KoDP?utm_source=share&utm_medium=member_desktop

**Comment by UrsuzEremita** [comment]
https://www.linkedin.com/posts/josue-sanchez-acosta-b94523292_github-ursuzeremitaproyectofinal-proyecto-activity-7134236182934102017-F6Vm?utm_source=share&utm_medium=member_desktop

**Comment by YukieTZ** [comment]
https://www.linkedin.com/feed/update/urn:li:share:7134613763260862464/
